apiVersion: v1
data:
  {{ .Values.dbPassword.key }}: {{ .Values.dbPassword.secret }}
kind: Secret
metadata:
  name: {{ .Values.dbPassword.name }}
  namespace: default
type: {{ .Values.dbPassword.type }}
