apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webApp.serviceName }}
  labels: 
    app: {{ .Values.webApp.labelApp }}
    service: {{ .Values.webApp.labelApp }}
spec:
  type: {{ .Values.webApp.serviceType }}
  ports:
  - name: tcp
    port: {{ .Values.webApp.servicePort }}
    targetPort: {{ .Values.webApp.targetPort }}
  selector:
    app: {{ .Values.webApp.labelApp }}
