kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: api-network
spec:
  podSelector:
    matchLabels:
      app: postgres
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: softcon-api