apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.api.deploymentName }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.api.deploymentName }}
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
