apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.deploymentName }}
  labels:
    app: {{ .Values.api.labelApp }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.api.labelApp }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.labelApp }}
    spec:
      containers:
      - name: {{ .Values.api.containerName }}
        image: {{ .Values.api.image }}
        ports:
        - containerPort: 5000
        resources:
          # You must specify requests for CPU to autoscale
          # based on CPU utilization
          requests:
            cpu: "100m"
        volumeMounts:
            - name: dbpwd
              mountPath: "/etc/db_pwd"
              readOnly: true
      volumes:
      - name: dbpwd
        secret:
          secretName: postgres-secret
