apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: db_admin_binding
  namespace: default
subjects:
- kind: User
  name: db_admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: db_admin
  apiGroup: rbac.authorization.k8s.io
