swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /orders:
    get:
      operationId: "orders.read_all"
      tags:
        - "Order"
      summary: "The orders data structure supported by the server application"
      description: "Read the list of orders"
      responses:
        200:
          description: "Successful read orders list operation"
          schema:
            type: "array"
            items:
              properties:
                id:
                    type: integer
                    description: Order ID 
                total:
                    type: integer
                    description: Total price for the order
                meals:
                    type: "array"
                    items:
                      properties:
                        meal_id:
                          type: "integer"
                        quantity:
                          type: "integer"
                    description: Meals included in order to create
                timestamp:
                  type: "string"
    post:
        operationId: orders.create
        tags:
            - Order
        summary: Create order
        description: Create
        parameters:
            - name: order
              in: body
              description: Order to create
              schema:
                  type: object
                  properties:
                      total:
                          type: integer
                          description: Total for the order
                      meals:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                              quantity:
                                type: integer
                          description: Meals included in order to create
        responses:
            201:
                description: Successfully created order in list



  /orders/{order_id}:
  #   get:
  #     operationId: "order.read_order"
  #     tags:
  #       - "Order"
  #     summary: "The order data structure supported by the server application"
  #     description: "Read the list of order"
  #     parameters:
  #         - name: order_id
  #           in: path
  #           type: id
  #           description: ID of order
  #           required: true
  #     responses:
  #       200:
  #         description: "Successful read order list operation"
  #         schema:
  #           type: "array"
  #           items:
  #             properties:
  #               total:
  #                 type: "int"
  #               meals:
  #                 type: "array"
  #                 items:
  #                   properties:
  #                     meal_id:
  #                       type: "integer"
  #                     quantity:
  #                       type: "integer"
  #                 description: Meals included in order to create
  #               timestamp:
  #                 type: "string"
    delete:
      operationId: orders.delete
      tags:
        - Order
      summary: The order data structure supported by the server application
      description: Delete order
      parameters:
          - name: order_id
            in: path
            type: integer
            description: Order ID
            required: true
      responses:
        200:
          description: Successful deleted order in order list
